switchtolayout;

write("single_data.txt","");

setnamed("source","z",0.26*1e-6);
setnamed("source","direction","Backward");

for(i=0:63){
setnamed("structures::rectangle"+num2str(i),"enabled",0);}
pixel_index=[4,9,28,32];
for(i=1:length(pixel_index)) { 
setnamed("structures::rectangle"+num2str(pixel_index(i)),"enabled",1);}

# incident from forward to backward
setnamed("source","polarization angle",0);
setnamed("source","x span",0.5*1e-6);
setnamed("source","y span",0.5*1e-6);
run;

x=getdata("front_monitor","x");
y=getdata("front_monitor","y");
f=getdata("front_monitor","f");
Exxff=integrate(pinch(getdata("front_monitor","Ex")),1:2,x,y)*1e12;
Eyxff=integrate(pinch(getdata("front_monitor","Ey")),1:2,x,y)*1e12;
Exxbf=integrate(pinch(getdata("back_monitor","Ex")),1:2,x,y)*1e12;
Eyxbf=integrate(pinch(getdata("back_monitor","Ey")),1:2,x,y)*1e12;
switchtolayout;
setnamed("source","polarization angle",90);
setnamed("source","x span",0.5*1e-6);
setnamed("source","y span",0.5*1e-6);
run;
Exyff=integrate(pinch(getdata("front_monitor","Ex")),1:2,x,y)*1e12;
Eyyff=integrate(pinch(getdata("front_monitor","Ey")),1:2,x,y)*1e12;
Exybf=integrate(pinch(getdata("back_monitor","Ex")),1:2,x,y)*1e12;
Eyybf=integrate(pinch(getdata("back_monitor","Ey")),1:2,x,y)*1e12;

# incident from backward to forward
switchtolayout;
setnamed("source","z",-0.5*1e-6);
setnamed("source","direction","Forward");
setnamed("source","polarization angle",0);
run;

Exxfb=integrate(pinch(getdata("front_monitor","Ex")),1:2,x,y)*1e12;
Eyxfb=integrate(pinch(getdata("front_monitor","Ey")),1:2,x,y)*1e12;
Exxbb=integrate(pinch(getdata("back_monitor","Ex")),1:2,x,y)*1e12;
Eyxbb=integrate(pinch(getdata("back_monitor","Ey")),1:2,x,y)*1e12;
switchtolayout;
setnamed("source","polarization angle",90);
run;
Exyfb=integrate(pinch(getdata("front_monitor","Ex")),1:2,x,y)*1e12;
Eyyfb=integrate(pinch(getdata("front_monitor","Ey")),1:2,x,y)*1e12;
Exybb=integrate(pinch(getdata("back_monitor","Ex")),1:2,x,y)*1e12;
Eyybb=integrate(pinch(getdata("back_monitor","Ey")),1:2,x,y)*1e12;

save_phase = matrix(103,16);
save_phase(1:103,1)=Exxff;
save_phase(1:103,2)=Eyyff;
save_phase(1:103,3)=Exyff;
save_phase(1:103,4)=Eyxff;
save_phase(1:103,5)=Exxbf;
save_phase(1:103,6)=Eyybf;
save_phase(1:103,7)=Exybf;
save_phase(1:103,8)=Eyxbf;
save_phase(1:103,9)=Exxfb;
save_phase(1:103,10)=Eyyfb;
save_phase(1:103,11)=Exyfb;
save_phase(1:103,12)=Eyxfb;
save_phase(1:103,13)=Exxbb;
save_phase(1:103,14)=Eyybb;
save_phase(1:103,15)=Exybb;
save_phase(1:103,16)=Eyxbb;
write('single_data.txt',num2str(pixel_index));
write('single_data.txt',num2str(save_phase));